### PR TITLE
Fix markdownlint warnings

### PR DESCRIPTION
**Pull request by qarkai**
Add alt text to Geeqie icon.
Remove obsolete `#requirements` link.
Also use code blocks instead of raw text for shell commands.

### CODE REVIEW

**Comment by caclark** [comment]
> Add alt text to Geeqie icon, also use link to local file.

I intentionally included the Geeqie icon as base64 text so that the icon shows if the README file is downloaded and viewed, even if  Geeqie is not installed.

The icon is also displayed if the user selects README from the Geeqie Help menu.

I know that the icon does not show on the GitHub page (I do not know why), but the Geeqie icon is shown elsewhere on that page.

Is it possible to have the alt-text and keep the icon within the file?

Are there any other people with for-or-against for this topic?

**Comment by qarkai** [comment]
I'll revert link to local file.

**Comment by qarkai** [comment]
Reverted.

**Comment by caclark** [comment]
Implemented in commit c106e4d7a5098ecd0ea4fcfd8eaf55cca6de0a70

**Pull request closed without merging**
