### PR TITLE
Let image loader backend decide how to process image buffer

### PR DESCRIPTION
**Pull request by qarkai**
Remove `ImageLoaderBackendFuncLoad`.
Also move static functions to anonymous namespace.

### CODE REVIEW

**Comment by caclark** [comment]
When I run `./scripts/test-all.sh` I get this error:


=================================== 68/73 ====================================
test:         Code Correctness_ image-load-tiff.cc
start time:   08:56:58
duration:     2.35s
result:       exit status 1
command:      MALLOC_PERTURB_=55 /usr/bin/clang-tidy -p ./build -quiet --config-file /home/cclark/data/geeqie/geeqie/.clang-tidy /home/cclark/data/geeqie/geeqie/src/image-load-tiff.cc
----------------------------------- stdout -----------------------------------
../src/image-load-tiff.cc:70:13: error: 'free_buffer' is a static definition in anonymous namespace; static is redundant here [readability-static-definition-in-anonymous-namespace,-warnings-as-errors]
static void free_buffer (guchar *pixels, gpointer)
~~~~~~~     ^
----------

The Code Correctness check should be run for pull requests, so there must be another problem there....

**Comment by qarkai** [comment]
> static void free_buffer (guchar *pixels, gpointer)

Fixed. Should I add new commit or amend previous? In other words are you going to squash commits before merge? I don't want broken commits in master branch.

> The Code Correctness check should be run for pull requests

Do you mean it should be run by GitHub? Looks like it doesn't.



> so there must be another problem there....

I missed this `static`, no other problem.



> When I run `./scripts/test-all.sh`

Is it possible to run this script for pull requests on GitHub?

**Comment by caclark** [comment]
> Fixed. Should I add new commit or amend previous? In other words are you going to squash commits before merge? I don't want broken commits in master branch.

I simply download the latest `<n>.patch` file and run `git am` on it.

>    so there must be another problem there....
>I missed this static, no other problem.

 I meant that I have made a mistake in setting up the GitHub tests.

> Is it possible to run this script for pull requests on GitHub?

I intended this script to be run locally. I will fix `meson.build` or wherever the problem is so that all pull requests run all relevant tests.

**Comment by qarkai** [comment]
> I simply download the latest `<n>.patch` file and run `git am` on it.

This recreates all commits. So I amended and force-pushed current commit.

**Comment by caclark** [comment]
Implemented in commit 5c0985aeec89

**Pull request closed without merging**
