### PR TITLE
some cleanups

### PR DESCRIPTION
**Pull request by neheb**
Not sure about some of these.

### CODE REVIEW

**Comment by tomaszg7** [comment]
Not sure about "auto with g_new". In Geeqie it was customary in the code to declare variables at the beginning of the function body. To be consistent one should get rid of most of those declarations. Not sure it is worth the effort and how it would affect readability of the code.

**Comment by neheb** [comment]
I meant the double pointer commit. Seems fishy.

**Comment by caclark** [comment]
@neheb 
Hello Rosen
The double pointer change is a problem - the current code, after an earlier cast change, is a bug.
Unfortunately these cast changes confuse me...

This is the original code, which works:
`GList *path = keyword_tree_get_path(keyword_tree, &child_iter);`
`gtk_selection_data_set(selection_data, gtk_selection_data_get_target(selection_data), 8, (gpointer) &path, sizeof(path));`

The current code is:
`GList *path = keyword_tree_get_path(keyword_tree, &child_iter);`
`gtk_selection_data_set(selection_data, gtk_selection_data_get_target(selection_data), 8, reinterpret_cast<const guchar *>(&path), sizeof(path));`

which crashes when executed.

I do not see the correct way to recast this. Do you have an idea?
Thanks...

**Comment by neheb** [comment]
Can't say I understand the code. The cast can be removed I think. The sizeof is operating on a pointer instead of the type.

If the parameter type is really a gpointer (void*). Cast can be removed or replaced with a const cast.

**Comment by neheb** [comment]
Maybe https://github.com/BestImageViewer/geeqie/commit/b5b655ddd8efdad56498cde402c7aa0f0afc86ac is a hint.

**Comment by neheb** [comment]
I just looked. I did not touch this code before.

**Comment by caclark** [comment]
I'm sorry, I misinformed you. The problem is in line 679 of bar-keywords.cc:
`//~ auto path = (GList *)(gtk_selection_data_get_data(selection_data));`
`GList *path = *(gpointer *)gtk_selection_data_get_data(selection_data);`

If you would like, I can try to fix it.

**Comment by neheb** [comment]
Just revert https://github.com/BestImageViewer/geeqie/commit/d4f7d83269fdb13acaa0e5bc25018a8bc75a0ee9

**Comment by neheb** [comment]
Reverted here.

**Comment by caclark** [comment]
Implemented in commits  ad80078 89f1d6cf 4eb87105 581e87f7

**Pull request closed without merging**
