### PR TITLE
Create image from icon name instead of stock id

### PR DESCRIPTION
**Pull request by qarkai**

### CODE REVIEW

**Comment by caclark** [comment]
Thanks. Implemented in commit bf5cd884

**Comment by tomaszg7** [comment]
That's a partial fix to the issue which I'm trying to solve more comprehensively in my branch https://github.com/BestImageViewer/geeqie/issues/1091 It replaces only a small part of deprecated stock id stuff in the codebase.

I'm sorry for my slow progress, there are still many things to be done. However I think I should try to wrap up at least a part of it cause it gets out of synth with master branch.

**Comment by qarkai** [comment]
Sorry for the inconvenience. You can create draft PR to mark your territory.

**Comment by tomaszg7** [comment]
I opened the issue to mark it, didn't start PR since it was not ready by far. Feel free to take a look at it, maybe you have remarks, ideas or fixes.

**Pull request closed without merging**
