### PR TITLE
include lua.hpp instead of .h

### PR DESCRIPTION
**Pull request by neheb**
It seems extern C is needed.

### CODE REVIEW

**Comment by xsdg** [comment]
As mentioned in the bug, given that `lua.hpp` is not present in lua's github, I don't feel like we should rely on its presence.  It would be more reliable to manually use `extern "C"` for those three includes.

**Comment by neheb** [comment]
lua.hpp is installed by Lua's Makefile.

**Comment by xsdg** [comment]
It sounds like you have extra context on this.  It would help if you'd add that to the bug.  I searched for a good long while and couldn't figure out where `lua.hpp` comes from.

That said, we don't have control over how distros (particularly Gentoo) choose to build or package lua.  Gentoo's build system [specifically points at the lua's github](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-lang/lua/metadata.xml).  People report that `lua.hpp` is present, but again, it's not clear how that happens, so it feels very tenuous to rely on.  `extern "C"` is easy and is guaranteed to work across distros.

**Comment by neheb** [comment]
If Gentoo is the issue, probably better to rely on the Lua wrap instead.

**Comment by neheb** [comment]
Another solution could be to upgrade to C++17 and use __has_include.

**Comment by caclark** [comment]
I am really unclear about this pull request. Is the overall opinion that it should be committed?

**Comment by neheb** [comment]
FWIW I found the error with https://github.com/neheb/geeqie/tree/cii

**Comment by xsdg** [comment]
Howdy, Colin.  Sorry that I'm disappearing and reappearing so much.

My opinion is that we should go with your original solution of adding an explicit `extern "C" { … }` to the existing three lus includes in Geeqie's `lua.cc`.

I feel like using `lua.hpp` adds distro compatibility risk for minimal benefit.

**Comment by neheb** [comment]
Updated.

**Comment by caclark** [comment]
@neheb @xsdg 
Hello Omari, Rosen

I have no understanding of this subject. Unfortunately it is necessary for someone else to make a decision here about what to commit.

There is the pull suggested by Rosen, and there is the "extern C"  solution listed here #1117.

What is the way forward - one, the other, both, neither?

My only comment is that the best solution is the one that keeps people happy, rather than one that is merely technically correct.

Thanks for any suggestions.

**Comment by neheb** [comment]
This PR does the extern C now.

**Comment by caclark** [comment]
Thanks. Implemented in commit a132645e

**Pull request closed without merging**
