### PR TITLE
Fixes corrupted rendering in PanView on hidpi displays

### PR DESCRIPTION
**Pull request by xsdg**
This is a 95% fix for #1316 .  There is still a bug where rendering corruption will show up if the user zooms all the way out, and will then persist even if they zoom back in again.

The crux of this fix is to account for the hidpi scaling factor in `rt_source_tile_render`.  This PR also adds a significant amount of comments to explain that function's somewhat non-intuitive API, as well as how it operates internally.

A future commit will update the variable names to be more descriptive.

### CODE REVIEW

**Comment by caclark** [comment]
Implemented in commits 68cf77cf6bd2 edb32c944f 27acd4cbc 5358cc39531 cbd60bb53ec 9fe066a09e1bf

**Comment by qarkai** [comment]
@xsdg I believe that master branch should not have intermediate work-in-progress commits. Since maintainer doesn't use squash-and-merge strategy would you mind squashing commits for the next pull request?

**Comment by caclark** [comment]
> Echoing https://www.reddit.com/r/learnprogramming/comments/9zgvlk/comment/ea942uh/
"My recommendation is that you only declare multiple per line if they represent
more or less the same thing, and are used together in such a way that they
logically belong to each other."

I am happy if anyone contributes anything, in any way, to the project.

The ability to have a GitHub action check that any pull request or commit complies with a set of standards I see as a great advantage over the old way of no checks - the downside is that there is inflexibility.

In this case here, my option would be to code as, for example:
`gint tile_h;`
`gint tile_w;`
`gint tile_x;`
`gint tile_y;`

This complies with the single line requirement and groups variables together.

My preference is to leave things as they are, and leave the big let-out option as `NOLINT`.

**Comment by qarkai** [comment]
If they "are used together in such a way that they logically belong to each other" then they probably could be combined in struct. For `gint x, y, w, h;` set there is already a `GdkRectangle`. Although it has width/height instead of w/h.

**Comment by xsdg** [comment]
@caclark Just to be clear, the only intent of that comment was to explain that specific commit (From working at a company, I'm in the habit of over-explaining situations where I make a judgment call to bypass automated checks like that)

I agree with you 100% that this automated check makes sense and that it shouldn't be modified.  That said, I think splitting those into separate lines reduces readability because nobody is going to read the declaration for `rx` and then get novel information from a different declaration for `ry` or `rw` or `rh`.  They all always go together.

@qarkai: Yes, a struct is the much better option basically throughout all of the rendering code.  My focus was to fix the bug in time to use panview for a photo job I needed to do over the weekend.  There is _so much_ cleanup that would make sense (both in terms of restructuring and renaming), and I'm planning to put time into it now that the main bug has been resolved.  Thanks for the tip about `GdkRectangle`

**Pull request closed without merging**
