### PR TITLE
fix build against exiv2-0.27.x

### LINKED ISSUE #654: geeqie fails to build against new exiv2 0.27
Hi,

On Mageia Cauldron geeqie 1.4 fails to build against new exiv2 0.27, see the attached build log:

[geeqie_build_log.txt](https://github.com/BestImageViewer/geeqie/files/2718653/geeqie_build_log.txt)

Regards,
David

### PR DESCRIPTION
**Pull request by Cogitri**
fixes #654

### CODE REVIEW

**Comment by iMichka** [comment]
Hi: I am one of the homebrew/linuxbrew maintainers.

I tested this patch and it fixed the build. I was able to install and launch geeqie on my mac.

We are now shipping geeqie with this patch. Could it be merged, and a new release be made so we have a stable version without patches? Thanks in advance!

**Comment by Cogitri** [comment]
Maybe someone with exiv <0.26 could also test this?

**Comment by iMichka** [comment]
We do not ship the older exiv version anymore, so I do not have it installed anymore. I could rebuild exiv from source if needed (though I have a quite busy schedule so probably next week only).

**Comment by Cogitri** [comment]
> I could rebuild exiv from source if needed (though I have a quite busy schedule so probably next week only).

Ah, no worries. I was just asking if someone still has that in his system because I've already upgraded Void Linux to exiv 0.26 so it'd be rather annoying to test previous versions.

**Comment by Cogitri** [comment]
Alright, [seems like Travis uses 0.25](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=exiv2&searchon=names), so that should be taken care of.

**Comment by caclark** [comment]
Implemented in latest commit at geeqie.org:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=f9213c8ad796cf4571b2606435c32753040ec645

**Pull request closed without merging**
