### PR TITLE
clang-tidy: C to C++ casts

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by xsdg** [comment]
Could you include in the commit message the command that you ran to generate this commit, please?  (With the understanding that there were some tweaks after the fact)

**Comment by neheb** [comment]
Done

**Comment by neheb** [comment]
The undo conversion commit is suspicious. Anyone know if it's correct?

**Comment by neheb** [comment]
What you're seeing is a difference between 32 and 64-bit builds. I tested on the former. I'll look into fixing this. The fix is probably just reinterpret_cast.

**Comment by neheb** [comment]
You guys should really set up CI for PRs. On Linux, macos, and maybe freebsd if it builds there.

**Comment by caclark** [comment]
Implemented in commits 5533498 d4f7d83 3ac742d 203b358

**Pull request closed without merging**
