### PR TITLE
clang-tidy fixes

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by caclark** [comment]
Hello Rosen

When applying `git am 1101.patch` I get these warnings:

Applying: clang-tidy: replace int with bool
Applying: meson: set cpp standard to 14
Applying: exiv2: use unique_ptr
.git/rebase-apply/patch:14: space before tab in indent.
        	image_ = std::move(image);
warning: 1 line adds whitespace errors.
Applying: clang-tidy: use override
Applying: clang-tidy: use nullptr
.git/rebase-apply/patch:158: space before tab in indent.
				  		GINT_TO_POINTER(n), nullptr);
.git/rebase-apply/patch:8733: space before tab in indent.
	 		osd_template_insert(vars, "height", nullptr, OSDT_NONE);
.git/rebase-apply/patch:8734: space before tab in indent.
	 		osd_template_insert(vars, "res", nullptr, OSDT_NONE);
.git/rebase-apply/patch:16200: space before tab in indent.
 		osd_template_insert(vars, "height", nullptr, OSDT_NONE);
.git/rebase-apply/patch:16201: space before tab in indent.
 		osd_template_insert(vars, "res", nullptr, OSDT_NONE);
warning: 5 lines add whitespace errors.

[The build-check action will now run on pull_requests also, but only for the Ubuntu-22.04 runner]

**Comment by neheb** [comment]
Hmm? Those are warnings

**Comment by caclark** [comment]
Implemented in commits e9904375 618a3f0d 4869d8e 3b9074dbf1 0a37a170

**Comment by tomaszg7** [comment]
I see some `NULL`s still in the code after this change, e.g. in `src/layout-util.cc`.

**Comment by neheb** [comment]
The remaining NULLs are in code not compiled locally. I can manually make the changes.

The C function thing makes no difference.

**Pull request closed without merging**
