### PR TITLE
Adds preliminary file clustering capability

### PR DESCRIPTION
**Pull request by xsdg**
What's here so far only works with ViewFileIcon.
To use:
 + Right-click on the FileList and switch to Icon view.
 + Select multiple icons.
 + Hit `<Insert>` to cluster them.
 + Hit `F2` on any element of a cluster to expand and collapse that cluster.

Next step is to add support for ViewFileList, and then to tie them into the larger style/keybinding system (instead of hard-coding things)

### CODE REVIEW

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

Am So den  9. Jul 2017 um 20:19 schrieb Omari Stephens:
> @xsdg requested your review on: BestImageViewer/geeqie#497 Adds preliminary file clustering capability.

What is that about the reviewing?

I did not try to compile myself, however, I think, the functionality is
cool. But the travis compile failed...

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAllii9gACgkQpnwKsYAZ
9qxx6gwAxncqgG7GPwkzAZy9Sud7HrmuW/pKdNVhv5C8Ka/H6K/697R4S1liwwox
j0dKPYyX8O+GKfmxOVZeCsfoRx+NkKwgkq9t+8jOMrIREiD3n6FjjBBURVFm7eXJ
gIv8z/gBLOhEue7NxrUKw26IH2KGqa4L0ZkpF5BqxQqHWqkIzcETfqEOUfDfrtZk
pHS6qwnB2XbY9BSxFjhnDUIQ+tCWE05nje7DOAeuEuPcJKRJ2AhEtgInb325wOS3
D2Wyinx3CnPrdHaAnk4dtJZaOMxqGDgzk/9jP1mYzJZ7ImDI7bNiveQM/zvvtvby
PFThsMnnNDDHyt5JwJJIGemuk85AjfLWMGUq1W8t19y4fuis+HMSseSODJCRXXaJ
KXPQydHi6avWfDFw2fZedtQS6B9GuuetfpYTjrhkQBf0Yw63Y6O4gS03LNLdHBbt
FhcON20AYEE1ShfLSmD/F9x+LnB8Fqyo1unbtKuvnLYltV34pgxL7JHMPC+vSZRN
LPkDqCbg
=K7sR
-----END PGP SIGNATURE-----

**Comment by xsdg** [comment]
@mowgli: Basically, I'm just looking for someone to take a super cursory look to point out any egregious mistakes that I might have made.  Of course, if someone wanted to do a more in-depth review, that would also be welcome, but I expect that folks have other things to spend their time on :o)  I'm happy to merge my own pull requests; it's just a matter of doing some minimal due-diligence, since another pair of eyes might find something that I completely forgot, or that I didn't realize was way off.

Below is one example of an oversight that I had made, that someone else might have noticed before I my change was merged.  I moved a file and (at the time) didn't know to update POTFILES.in.  And more recently, I moved a file and knew to update POTFILES.in, but I forgot anyway :o(

    commit 6385be22a0be36111311269418c23405d4407401
    Author: Tomasz Golinski <tomaszg@math.uwb.edu.pl>
    Date:   Sun Jan 8 16:43:39 2017 +0100
    
        Correct the location of pan-view files in POTFILES.in
        
        Commit 58d397efc9e99104d21ea686837396673939ccde didn't update corresponding entries in POTFILES.in

**Comment by xsdg** [comment]
Oh, and yeah, the build breakage is expected.  I'm probably going to make sure that everything compiles in C99 mode, and then suggest that we switch to C99 mode.  For me, it's worth it even if just to do variable declarations inside of a for loop (which is what I did that travis doesn't like right now).  Restricting variable scope helps a lot to keep things nice and tidy.  So something like this:

    GList *work = list;
    while (work)
        {
        GList *other_work = other_list;
        FileData *fd = work->data;
        work = work->next;
        while (other_work)
            {
            FileData *other_fd = other_work->data;
            other_work = other_work->next;
            […]
            }
        }

turns into something like this:

    for (GList *work = list; work; work = work->next)
        {
        FileData *fd = work->data;
        for (GList *other_work = other_list; other_work; other_work = other_work->next)
            {
            FileData *other_fd = other_work->data;
            […]
            }
        }

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi Omari,

Am So den  9. Jul 2017 um 22:02 schrieb Omari Stephens:
> @mowgli: Basically, I'm just looking for someone to take a super cursory look to point out any egregious mistakes that I might have made.  Of course, if someone wanted to do a more in-depth review, that would also be welcome,

Ah, ok. I just didn't know this feature of github. Now I search for a
way to do it from the command line as I hate web to do stuff.

> but I expect that folks have other things to spend their time on :o)

Yea, like flying. ;-)

Regards
   Klaus
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAlljJiEACgkQpnwKsYAZ
9qwQagv9FnF+2rE6F8v6Fpe01Hf1Sl8rRdupxr2xIy2fYium0YY2gRlStIHWyN5y
pYJ66Ro9QrFhT+IfzjLvLCALt/R3+detOaiHKDFQc5XHzMCFgJnCipGiTNIeag8W
EHWjaFecg4gOwZMm0Iq/fthI754zf0kxvk4spGx7DyK7TX4UrkEaj9EITI61HtOB
vxTSxUT3HnCa9W4oRkatcXQFQOCl+vRP80RHLK94CUngDFZ8xG3fHY+Y5CTc19XS
oro2OVpr+7m1T+6MmqDp9ec5nwR7jtKKEsoDEEL2Wq1cn5wy6m497RcylJDiEL7W
1ShejLYhPolM7CHylVN6UrBvh9MPZxYkjev61DNl7zZQ0/UKOn1tx0Gq1Dju9Cbw
MP9OuBlcWiw8zEQTmuG2foxah22m+Pck2PY+84fhSHNx1mxBXIvkaySBVi1uqFJc
N2fqcFFLZQDY2cgPjarS+9/vW7Ejx/tcvsfTGbavhrA04qJSLm+QrtmJpSNYgwjd
saVYBgNo
=Emm0
-----END PGP SIGNATURE-----

**Comment by xsdg** [comment]
@mowgli: I agree with all of your thoughts.  In case it weren't clear, this pull request is for a new working branch I created in the BestImageViewer project.  It's definitely not yet ready to go into master.

**Comment by xsdg** [comment]
@mowgli: Added modelines to filecluster.{c,h}

**Pull request merged**
