### PR TITLE
Creates a more-explicitly-type-unsafe value reader for enums

### PR DESCRIPTION
**Pull request by xsdg**
Also fixes a potential use-before-define issue by adjusting how we parse the `<filter_type>` element within the `<class_filter>` element of the geeqie config

### CODE REVIEW

**Comment by caclark** [comment]
I get a couple of warnings and errors in rcfile.c:
[1016-1.log.gz](https://github.com/BestImageViewer/geeqie/files/9232347/1016-1.log.gz)

**Comment by xsdg** [comment]
This... wasn't my best work.  Thanks for checking.

I think it should be good to go now, but I couldn't figure out how to get this code to run, even though my config includes:
```
        <class_filter>
            <filter_type filter = "Unknown" enabled = "true" />
            <filter_type filter = "Image" enabled = "true" />
            <filter_type filter = "RAW Image" enabled = "true" />
            <filter_type filter = "Metadata" enabled = "true" />
            <filter_type filter = "Video" enabled = "true" />
            <filter_type filter = "Collection" enabled = "true" />
            <filter_type filter = "Document" enabled = "true" />
            <filter_type filter = "Archive" enabled = "true" />
        </class_filter>
```

**Comment by caclark** [comment]
> but I couldn't figure out how to get this code to run, even though my config includes:

I'm sorry, but I do not understand... Are you saying that `class_filter_load_filter_type()` is not executed?

**Comment by xsdg** [comment]
That's correct.  I added some log lines that I wasn't seeing, so then I added an `abort()` and that also didn't get triggered.

Here's an excerpt from the log from my run (https://justpaste.it/97qgi):
```
16:47:56> [xsdg{angular}@~/files/compile/photos/gqpp]
$./build/src/geeqie --debug=1 -n ~/files/dl/test/
[...]
    0.212109 (+00000.000224) main: load_options
loader reported [ani] [Windows animated cursor] [.ani]
loader reported [bmp] [BMP] [.bmp]
loader reported [gif] [GIF] [.gif]
loader reported [icns] [MacOS X icon] [.icns]
loader reported [ico] [Windows icon] [.ico;.cur]
loader reported [jpeg] [JPEG] [.jpeg;.jpe;.jpg]
loader reported [png] [PNG] [.png]
loader reported [pnm] [PNM/PBM/PGM/PPM] [.pnm;.pbm;.pgm;.ppm]
loader reported [qtif] [QuickTime] [.qtif;.qif]
loader reported [svg] [Scalable Vector Graphics] [.svg;.svgz;.svg.gz]
loader reported [tga] [Targa] [.tga;.targa]
loader reported [tiff] [TIFF] [.tiff;.tif]
loader reported [xbm] [XBM] [.xbm]
loader reported [xpm] [XPM] [.xpm]
Loading options from /home/xsdg/.config/geeqie/geeqierc.xml ... done
```

So it seems like it should be running that code, but I didn't see evidence of it being run.

**Comment by caclark** [comment]
My method is to insert `DEBUG_0()` statements everywhere, and run with no higher debug level.
This is the total diff I used. It seems ok to me.
[1016-3.diff.gz](https://github.com/BestImageViewer/geeqie/files/9258118/1016-3.diff.gz)

**Comment by caclark** [comment]
Fixed in commits 45c4e5e9 97b889845 97b941e 3dfd62116

**Pull request closed without merging**
