### PR TITLE
Use filelist_copy to reduce duplication

### PR DESCRIPTION
**Pull request by qarkai**
Simplify related code.

### CODE REVIEW

**Comment by caclark** [comment]
Implemented in commit 9c740415fbf

**Comment by caclark** [comment]
@qarkai 
Hello Arkadiy

I think there is a problem. If I right-click on an item in the files pane, there is a seg. fault.

[When I use git to revert the commit, the problem goes away. When I revert the commits by hand, the bug still exists....
Strange. But something is amiss somewhere.]

**Comment by qarkai** [comment]
@caclark I messed with lists concatenation. I'l fix it now.

**Comment by qarkai** [comment]
Fix in #1179.

**Pull request closed without merging**
